---
app:
  information:
    name: APP1
    description: Simple API to demonstrate how to create a simple spring cloud project
info:
  app:
    name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: ['*']
